language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly

# script:
#   # Default Travis script uses the more or less the following with Project.toml
#   - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

# TODO: modernize doc building to use Project.toml for Documenter.
jobs:
  include:
    - stage: deploy
      julia: 1.0
      os: linux
      script:
        - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("AxisArrays")'
        - julia -e 'import Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); Pkg.add("Unitful")'
        - julia -e 'import AxisArrays; ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs","make.jl"))'

after_success:
#  - julia -e 'Pkg.add("Unitful")' ?
  - if [ $TRAVIS_JULIA_VERSION = "1.0" ] && [ $TRAVIS_OS_NAME = "linux" ]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
    fi
